# Create a Pod and then expose it using Service
kind: Service
apiVersion: v1
metadata:
  name: dotnetcore-homepge-docker-k8s-service
spec:
  type: NodePort
  selector:
    app: dotnetcore-homepge-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80