kind: Pod
apiVersion: v1
metadata:
  name: kube-dotnet-app-pod
  labels:
    app: kube-dotnet-app
spec:
  containers:
    - name: kube-dotnet-app-container
      image: ananddeshmukhalm/dotnetcore-homepge-docker-k8s:linux
      
---
kind: Service
apiVersion: v1
metadata:
  name: kube-dotnet-app-service
spec:
  type: NodePort
  selector:
    app: kube-dotnet-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
