apiVersion: extensions/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-11-19T21:55:59Z
  generation: 1
  labels:
    run: first-deployment
  name: first-deployment
  namespace: default
  resourceVersion: "300379"
  #selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/first-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: first-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: first-deployment
    spec:
      containers:
      - image: katacoda/docker-http-server
        imagePullPolicy: Always
        name: first-deployment
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30