# Create a Pod and then expose it using Service
kind: Service
apiVersion: v1
metadata:
  name: eshop-mvc-app-k8s-service
spec:
  type: NodePort
  selector:
    app: eshop-mvc-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80